# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  timeout: 5m
  skip-dirs:
    - test
  tests: false
linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - wrapcheck
  fast: false
linters-settings:
  gocritic:
    enabled-tags:
      - style
      - experimental
      - performance
      - diagnostic
      - opinionated

  govet:
    enable-all: true
    disable:
      - shadow

  gci:
    local-prefixes: github.com/loghole/dbhook
